### ISSUE TITLE
Running into error in colab, when running main script

### ISSUE THREAD

**Issue by gelsas** [johnGettings/LIHQ#5]
Hi I am receiving ths error when trying to run the main script

```
/content/LIHQ
Initializing
Moviepy - Building video ./first_order_model/input-ref-vid/Folder1/Folder1.mp4.
Moviepy - Writing video ./first_order_model/input-ref-vid/Folder1/Folder1.mp4

Moviepy - Done !
Moviepy - video ready ./first_order_model/input-ref-vid/Folder1/Folder1.mp4
Running First Order Motion Model
100%
569/569 [00:21<00:00, 25.00it/s]
FOMM Success!
Running Wav2Lip
Wav2Lip could not generate at least one of your videos.
Possibly bad audio, unrecognizable mouth, bad file paths, out of memory.
Run below command in a separate cell to get full traceback.
###########################################################
###########################################################
import os
adir = 'Folder1' # The audio folder that failed. See Wav2Lip output folder to see whats missing.

vid_path = f'{os.getcwd()}/output/FOMM/Round1/{adir}.mp4'
aud_path = f'{os.getcwd()}/input/audio/{adir}/{adir}.wav'
%cd /content/LIHQ/Wav2Lip
!python inference.py --checkpoint_path ./checkpoints/wav2lip.pth --face {vid_path} --audio {aud_path} --outfile /content/test.mp4  --pads 0 20 0 0


An exception has occurred, use %tb to see the full traceback.

SystemExit
```

When tryin to run the command as suggested in the comment I get this:

The command I ran:

```
%cd /content/LIHQ
import os
adir = 'Folder1' # The audio folder that failed. See Wav2Lip output folder to see whats missing.

vid_path = f'{os.getcwd()}/output/FOMM/Round1/{adir}.mp4'
aud_path = f'{os.getcwd()}/input/audio/{adir}/{adir}.wav'
%cd /content/LIHQ/Wav2Lip
!python inference.py --checkpoint_path ./checkpoints/wav2lip.pth --face {vid_path} --audio {aud_path} --outfile /content/test.mp4  --pads 0 20 0 0
```

The error it shows:

```
/content/LIHQ
/content/LIHQ/Wav2Lip
Using cuda for inference.
Reading video frames...
Number of frames available for inference: 569
Traceback (most recent call last):
  File "/content/LIHQ/Wav2Lip/inference.py", line 280, in <module>
    main()
  File "/content/LIHQ/Wav2Lip/inference.py", line 225, in main
    mel = audio.melspectrogram(wav)
  File "/content/LIHQ/Wav2Lip/audio.py", line 47, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hp.ref_level_db
  File "/content/LIHQ/Wav2Lip/audio.py", line 95, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/content/LIHQ/Wav2Lip/audio.py", line 100, in _build_mel_basis
    return librosa.filters.mel(hp.sample_rate, hp.n_fft, n_mels=hp.num_mels,
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
```

Could you help me understand what the issue is and how to fix it ?

**Comment by ms-kumar** [comment]
U are using latest version, replace mel() function as describe hare : https://stackoverflow.com/a/76177078/21977633

**Comment by johnGettings** [comment]
Hi. Thank you both.
I rolled back the librosa version to 0.9.1 in requirements.txt

Seems to be working for me now. Let me know if it's not resolved.
